### ISSUE TITLE
xarray 0.16.1 breaks compatibility

### ISSUE THREAD

**Issue by kiudee** [arviz-devs/arviz#1387]
**Describe the bug**
`arviz.utils.HtmlTemplate` depends on `xarray.core.formatting_html.CSS_STYLE`:
https://github.com/arviz-devs/arviz/blob/aab82191677c0ead4cceee3a0198f0afcd7313a4/arviz/utils.py#L700
This was just removed in 0.16.1 of xarray. Here is the corresponding pull request:
https://github.com/pydata/xarray/pull/4297

**To Reproduce**

1. Install `arviz==0.9.0` and `xarray==0.16.1`.
2. `import arviz`

**Expected behavior**
No error during import.

**Additional context**
`arviz==0.9.0` and `xarray==0.16.1`.
Happens on both Windows and Linux.

**Comment by ahartikainen** [comment]
We are going to make a new release soon, so this is probably going to be only a small annoyance until we have release ready.

**Comment by ahartikainen** [comment]
fixed by #1389

**Comment by nicospinu** [comment]
Hi, the issue still persists on macOS Catalina v.10.15.6 giving the same message as described by kiudee. Shall I create a new issue?

**Comment by kiudee** [comment]
@nicospinu the fix is not yet on PyPI (still v0.9.0) there.

**Comment by nicospinu** [comment]
I have installed Pymc3 that depends on Arviz. I want to use the latest version of Pymc3 and hence, any suggestions will be highly appreciated

**Comment by nicospinu** [comment]
> have you tried installing from github
> 
> ```
> pip install git+https://github.com/arviz-devs/arviz
> ```

Thank you!
The Arviz gets installed together with Pymc3 v3.9.3 and gives the error. Shall I wait until the fix is on PyPI?

**Comment by ahartikainen** [comment]
then you can do

    pip install xarray==0.16.0 -U

**Comment by nicospinu** [comment]
Thank you so much! It works
