### ISSUE TITLE
Conda forge packages for arvizverse

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#2498]
The new modular structure with the 3 subpackages relies heavily on pip's bundles of optional dependencies. Conda doesn’t allow optional dependencies, but we can have extra packages to “compensate”. For example, matplotlib has matplotlib-base which has not backend and is recommended for downstreams to depend on and matplotlib which includes a recommended backend for users.

We currently have the following conda->pip equivalences
* arviz-base -> arviz-base
* arviz-stats -> arviz-stats[xarray]
* arviz-plots -> arviz-plots

We definitely need to update the dependencies of the already existing `arviz` package on conda forge. However I am not completely sure to what.

We could also add:
* arviz-stats-core -> arviz-stats
* arviz -> arviz[matplotlib]?
* arviz-plotly -> arviz[plotly] (most relevant for plotly because conda install arviz/arviz-plots plotly won’t work due to webcolors dependency missing)
* arviz-bokeh -> arviz[bokeh]

Having more feedstocks isn't a huge overhead but it takes some resources on conda forge's side and we'll also have to review their recipes every time we make a release even if the review is short.

**Comment by SachinDurairaj06** [comment]
Hi! I’d like to help with this issue. 
Before starting, could you clarify what scope you’re looking for here 
(e.g., new conda-forge feedstocks, updates to existing recipes, or documentation)?
I want to make sure I approach it correctly.

**Comment by aloctavodia** [comment]
Thanks @SachinDurairaj06. Currently we have 3 conda-forge packages  

arviz-base
arviz-stats
arviz-plots

Given that conda is unable to manage optional dependecies, we could create more packages with variations of those dependencies. First we need to decide which new packages we want and then add them to conda-forge.

These are new

arviz-stats-core (other names could be arviz-stats-array, arviz-stats-lite)
arviz-plotly
arviz-bokeh 

And this already exists and needs to be updated.

arviz

**Comment by SachinDurairaj06** [comment]
Thanks for the clarification!  
To keep the scope manageable, I’d like to start with creating a conda-forge package for `arviz-stats-core`.  
Please let me know if that sounds reasonable before I proceed.

**Comment by aloctavodia** [comment]
Maybe start from a different one. I am not sure about the name arviz-stats-core

**Comment by SachinDurairaj06** [comment]
Thanks for pointing that out.
To avoid ambiguity, I’m happy to start with a more established package.
Would starting with a conda-forge package for `arviz-stats` be a better option?
Please let me know what you’d recommend as the best first target.

**Comment by aloctavodia** [comment]
We already have 

arviz-base
arviz-stats
arviz-plots
arviz (this likely needs to be updated)

You can start with arviz-plotly.

**Comment by SachinDurairaj06** [comment]
Great, thanks for confirming!

I’ll start with arviz-plotly.

My next steps will be:

Inspect how the Plotly backend is currently handled inside arviz-plots

Identify the minimal dependencies required for Plotly

Create a new arviz-plotly conda-forge feedstock

Check whether the main arviz meta-package needs updates to reference it

I’ll share progress or questions here as I go.

**Comment by SachinDurairaj06** [comment]
I’ve located all Plotly-specific code under
src/arviz_plots/backend/plotly/ (core, legend, templates, etc.), which looks cleanly isolated.

My proposal is to move this backend into a new arviz-plotly package, keeping backend registration in arviz-plots.

Expected dependencies would be plotly (and possibly kaleido) plus the existing ArviZ base requirements.

Next step for me would be drafting a minimal conda-forge recipe for arviz-plotly. Please let me know if that matches your expectations.

**Comment by aloctavodia** [comment]
No need to move any code. We just need a way to install different plotting backends.

**Comment by SachinDurairaj06** [comment]
Okay i will work on it rihgtn ow

**Comment by SachinDurairaj06** [comment]
I implemented the proposed `arviz-plotly` meta-package on conda-forge.

PR: https://github.com/conda-forge/staged-recipes/pull/31802

The package provides a clean conda equivalent for `arviz[plotly]` without optional dependencies
and passes all CI checks across platforms.

Thanks for the guidance in this issue!

**Comment by OriolAbril** [comment]
Sorry I missed the last few days of the conversation. I was a bit confusing in the initial issue description due to not being a conda expert and still not being sure what we should do exactly. I added the "discussion" label to signal some extra conversation was probably needed before jumping on a PR but I wasn't clear on that in the description, and the "help wanted" label arguably signals the exact oppsite.

I think for the most part, we should follow matplotlib's example. If you search for it, you'll see there is no `matplotlib-base-feedstock` repository. Both `matplotlib` and `matplotlib-base` are conda packages, but both their recipes are defined in https://github.com/conda-forge/matplotlib-feedstock/blob/main/recipe/meta.yaml as there are two outputs defined. Therefore, I don't think there will be a scenario where we'll want to have an independent `arviz-plotly-feedstock` repo on conda forge.

**Open questions:**

1. **To what will `arviz` conda package be updated to?**
2. **It looks like there is consensus in adding `arviz-plotly` and `arviz-bokeh` packages. Do we want these as extra outputs of `arviz` or of `arviz-plots`? (this answer will most probably depend on the previous answer)**
3. **It also seems there is some consensus around having two packages for arviz-stats so we'll need to update the recipe to have the two outputs. What name should we give the package that installs `arviz-stats+numpy` without `xarray`?**

Possible answers:

1. Given `arviz` has so far always had matplotlib as a non-optional dependency, the least distruptive update is probably updating it so install conda's `arviz` package installs arviz-plots and matplotlib
2. I think these should be outputs of the `arviz` feedstock which would then have 3 outputs: `arviz` output with mpl backend, and these two
3. I am horrible with names but the two proposed by @aloctavodia do sound a bit better I think.

---

For the sake of completeness, I did skim through the feedstock PR, so here is some high level feedback.

> Inspect how the Plotly backend is currently handled inside arviz-plots
> Identify the minimal dependencies required for Plotly

The key pieces here are the arviz-plots [pyproject.toml](https://github.com/arviz-devs/arviz-plots/blob/c1343e6681b8e39fbe763d8cb370894c7872464a/pyproject.toml#L45) and [arviz one](https://github.com/arviz-devs/arviz/blob/main/pyproject.toml#L49). We want `arviz-plotly` in conda to be equivalent to `arviz[plotly]`, and we have `arviz[plotly]` available even though it is as complicated (or even a bit more complicated) than `pip install arviz plotly` because to maintain feature parity between backends we sometimes need extra dependencies in addition to the backend itself. In plotly's case, for its arviz backend to work we also need `webcolors` to be installed. This means the `arviz-plotly` package needs to install `arviz-plots`, `plotly` and `webcolors`.

kaleido is a dependency commonly installed along plotly to store its plots as png or svg, but in arviz's case it is irrelevant. ArviZ generates plotly figures; how these figures are rendered or stored is 100% left to the plotting backend. Therefore, if someone wants to store plotly outputs as png they will have to manually install kaleido (or try saving as png and failing in which case _plotly_, not arviz, will error out saying kaleido is needed).

**Comment by SachinDurairaj06** [comment]
Thanks for the clarification, this makes sense.

I agree that following matplotlib’s approach with multiple outputs in a single feedstock is the right long-term solution. My PR was mainly intended to explore the dependency surface and validate what arviz[plotly] requires on conda-forge.

From the investigation:
- Minimal Plotly backend deps appear to be arviz-plots, plotly, and webcolors
- kaleido is not required for ArviZ itself

I’m happy to pause further changes here and help refactor this into the appropriate feedstock/output structure once there’s consensus on:
- where the outputs should live (arviz vs arviz-plots)
- naming for the arviz-stats split

Let me know how you’d like to proceed.

**Comment by patelshivani2283-lab** [comment]
Hi everyone! I’d like to help with this issue.
From the discussion, it looks like arviz-plotly is the next step for aligning conda packages with pip’s optional dependencies. I’m happy to help by:

Testing the current arviz-plotly feedstock,

Drafting or refining the conda recipe for arviz-plotly,

Ensuring it installs arviz-plots, plotly, and webcolors correctly without optional dependencies.
Please let me know if I can start working on this or if there’s a preferred approach for the feedstock.

**Comment by OriolAbril** [comment]
Thanks @patelshivani2283-lab. I have assigned this to me because of the couple points that need discussion and the fact it is good to have admin access to work on this but I will comment back here when I finally get to this to get user testing on the result.

**Comment by OriolAbril** [comment]
Current state on conda forge (with all packages already published):

| conda forge | PyPI |
|---|---|
| arviz-base | arviz-base |
| arviz-stats-core | arviz-stats |
| arviz-stats | arviz-stats[xarray] |
| arviz-plots | arviz-plots |
| arviz | arviz[matplotlib] |
| arviz-bokeh | arviz[bokeh] |
| arviz-plotly | arviz[plotly] |
