### ISSUE TITLE
Spurious argument warning in plot_trace

### ISSUE THREAD

**Issue by fonnesbeck** [arviz-devs/arviz#988]
**Describe the bug**

Using `plot_trace` in arviz 0.6.2 generates the following warning:

```
/home/fonnesbeck/anaconda3/envs/bayes_course/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/distplot.py:38: UserWarning: Argument backend_kwargs has not effect in matplotlib.plot_distSupplied value won't be used
  "Argument backend_kwargs has not effect in matplotlib.plot_dist"
```

This happens repeatedly, but here is one example of the call:

```
plot_trace(trace_u, var_names=['β1', 'σ']);
```

As you can see, there are no `backend_kwargs` being passed, so the warning should not be shown.

As a minor additional issue, it should say "no effect" rather than "not effect".

**Comment by ahartikainen** [comment]
Error is in lines 274 & 290

https://github.com/arviz-devs/arviz/blob/master/arviz/plots/backends/matplotlib/traceplot.py

**Comment by nitishp25** [comment]
I think this issue has been resolved in PR #989 right?

**Comment by aakhmetz** [comment]
Sorry, but I still have this warning with the latest github-version of arviz
```python
az.plot_trace(trace, var_names=vars_)
```
gives the warning:
```python
/home/aakhmetz/anaconda3/lib/python3.6/site-packages/arviz/plots/backends/matplotlib/distplot.py:38: UserWarning: Argument backend_kwargs has not effect in matplotlib.plot_distSupplied value won't be used
  "Argument backend_kwargs has not effect in matplotlib.plot_dist"
```

**Comment by ahartikainen** [comment]
How did you install latest github version?

**Comment by aakhmetz** [comment]
by ```pip install git+https://github.com/arviz-devs/arviz```

**Comment by ahartikainen** [comment]
Hmm what does this say?

    which pip

or can you try

    python -m pip install git+https://github.com/arviz-devs/arviz

**Comment by aakhmetz** [comment]
```which pip``` gives ```/home/aakhmetz/anaconda3/bin/pip```

**Comment by ahartikainen** [comment]
Interesting. I can not reproduce your example.

**Comment by aakhmetz** [comment]
Yes, I was quite unsure whether I need to post, but I have had that message
on one of my ubuntu workstations, and it continued to re-appear even when I
reinstalled both pymc3 and arviz. It looks like there is something wrong
with my installation.

Thank you for checking!

**Comment by erickmartinez** [comment]
I installed pymc3 using miniconda's distribution (conda install pymc3) and I reproduced the same error when calling

pm.traceplot(trace)

"Argument backend_kwargs has not effect in matplotlib.plot_dist"
/path/to/miniconda3/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/distplot.py:38: UserWarning: Argument backend_kwargs has not effect in matplotlib.plot_distSupplied value won't be used

I am executing python 3.7 through ssh in a workstation using X11 forwarding.

**Comment by AlexAndorra** [comment]
Hi,
Thanks for the report. Do you know which version of ArviZ is on your virtual env? 
It should be fixed of you update to >= 0.7.0.

**Comment by erickmartinez** [comment]
Thanks Alexandre,

I had the following version installed:
-------------------------------------------------------
arviz                     0.6.1                      py_0

I just updated to 0.8.1 from conda-forge and the issue resolved.

Erick
